site_name: ProofOfThought
site_description: LLM-based reasoning using Z3 theorem proving
site_author: Debargha Ganguly
site_url: https://debarghaG.github.io/proofofthought

repo_name: debarghaG/proofofthought
repo_url: https://github.com/debarghaG/proofofthought
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

nav:
  - Home: index.md
  - Installation: installation.md
  - API Reference: api-reference.md
  - Backends: backends.md
  - Examples: examples.md
  - Benchmarks: benchmarks.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/debarghaG/proofofthought
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/proofofthought/

copyright: Copyright &copy; 2025 Debargha Ganguly
