[tool.black]
line-length = 100
target-version = ["py312"]

[tool.ruff]
# Ruff is used for linting; Black remains the formatter.
target-version = "py312"
line-length = 100

[tool.ruff.lint]
# Core rule sets: pycodestyle/pyflakes/imports/pyupgrade/bugbear
select = ["E", "F", "I", "UP", "B"]
ignore = ["E203", "E501"]

[tool.mypy]
python_version = "3.12"
# Reasonable strictness for a new integration
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
warn_unused_ignores = true
warn_redundant_casts = true
no_implicit_optional = true
# Many ML/DS libs lack type hints; relax imports to avoid noise
ignore_missing_imports = true
# Skip virtual environment
exclude = "env/"
